services:
  - type: web
    name: dreamdb-embedder-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python service.py
    envVars:
      - key: PORT
        value: "6789"